export const FETCH_SIMS_REQUEST = 'FETCH_SIMS_REQUEST';
export const FETCH_SIMS_SUCCESS = 'FETCH_SIMS_SUCCESS';
export const FETCH_SIMS_FAILURE = 'FETCH_SIMS_FAILURE';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
export const RESTORE_SIMS = 'RESTORE_SIMS';